version: '3.7'

services:
    web:
        build: .
        command: gunicorn divelog_server_project.wsgi:application --blind 0.0.0.0:8000 --workers 4
        volumes: 
            - .:/code
        ports: 
            - 8000:8000
        depends_on: 
            - db
    
    db:
        image: postgres:11
        volumes: 
            - postgres_data:/var/lib/postgres/data/

volumes: 
    postgres_data: